// Generate Ren'Py project files from a Project.
// Returns a map of path -> file content.

import type { Project, Scene, ScriptLine, Character } from "./types";

function slug(s: string): string {
  return (
    s
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "_")
      .replace(/^_+|_+$/g, "") || "x"
  );
}

function safeText(s: string): string {
  return (s ?? "").replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function characterVar(c: Character): string {
  return slug(c.name);
}

function renderLine(line: ScriptLine, project: Project): string {
  switch (line.type) {
    case "dialogue": {
      const c = project.characters.find((x) => x.id === line.characterId);
      const v = c ? characterVar(c) : "narrator";
      const expr = line.expression && c ? ` ${slug(c.name)}_${slug(line.expression)}` : "";
      const show = expr ? `    show${expr} at center\n` : "";
      const voice = line.voiceUrl ? `    voice "audio/voice/${line.id}.wav"\n` : "";
      return `${show}${voice}    ${v} "${safeText(line.text)}"`;
    }
    case "narration": {
      const voice = line.voiceUrl ? `    voice "audio/voice/${line.id}.wav"\n` : "";
      return `${voice}    "${safeText(line.text)}"`;
    }
    case "choice": {
      if (!line.choices?.length) return `    # (empty choice)`;
      const opts = line.choices
        .map(
          (c) =>
            `        "${safeText(c.label)}":\n            jump ${c.gotoSceneId ? scene_label(c.gotoSceneId) : "end"}`,
        )
        .join("\n");
      return `    menu:\n${opts}`;
    }
    case "sfx":
      return `    play sound "audio/sfx/${slug(line.text)}.wav"`;
    case "music":
      return `    play music "audio/music/${slug(line.text)}.wav" fadeout 1.0 fadein 1.0`;
    case "transition":
      return `    with ${line.text || "dissolve"}`;
    case "show": {
      const c = project.characters.find((x) => x.id === line.characterId);
      if (!c) return `    # show (no character)`;
      const expr = line.expression ?? "neutral";
      return `    show ${slug(c.name)}_${slug(expr)} at center`;
    }
    case "hide": {
      const c = project.characters.find((x) => x.id === line.characterId);
      if (!c) return `    # hide`;
      return `    hide ${slug(c.name)}`;
    }
    case "note":
      return `    # ${(line.text ?? "").replace(/\n/g, " ")}`;
  }
}

function scene_label(sceneId: string): string {
  return `scene_${sceneId}`;
}

export function renderSceneRpy(scene: Scene, project: Project): string {
  const bgAsset = project.assets.find(
    (a) => a.id === scene.background && a.kind === "background",
  );
  const bgLine = bgAsset
    ? `    scene bg ${slug(bgAsset.name)}`
    : scene.background
      ? `    scene bg ${slug(scene.background)}`
      : `    scene black`;
  const musicAsset = project.assets.find(
    (a) => a.id === scene.music && (a.kind === "music" || a.kind === "sfx"),
  );
  const musicLine = musicAsset
    ? `    play music "audio/music/${slug(musicAsset.name)}.wav" fadeout 1 fadein 1`
    : scene.music
      ? `    play music "audio/music/${slug(scene.music)}.wav" fadeout 1 fadein 1`
      : "";
  const header = [
    `label ${scene_label(scene.id)}:`,
    bgLine,
    musicLine,
    scene.ambient ? `    play ambient "audio/ambient/${slug(scene.ambient)}.wav"` : "",
  ]
    .filter(Boolean)
    .join("\n");
  const body = scene.lines.map((l) => renderLine(l, project)).join("\n");
  return `${header}\n${body}\n    return\n`;
}

export function renderCharactersRpy(project: Project): string {
  const defs = project.characters
    .map(
      (c) =>
        `define ${characterVar(c)} = Character("${safeText(c.name)}", color="#ffffff")`,
    )
    .join("\n");
  const images = project.characters
    .flatMap((c) =>
      c.expressions.map(
        (e) =>
          `image ${slug(c.name)}_${slug(e.name)} = "images/${slug(c.name)}/${slug(e.name)}.png"`,
      ),
    )
    .join("\n");
  return [
    "# Auto-generated by VN Builder Studio",
    'define narrator = Character(None, kind=nvl)',
    defs,
    "",
    "# Character expression images",
    images,
    "",
  ].join("\n");
}

export function renderScriptRpy(project: Project): string {
  const start = project.scenes[0];
  const begin = start
    ? `label start:\n    jump ${scene_label(start.id)}\n`
    : `label start:\n    "No scenes yet."\n    return\n`;
  const scenes = project.scenes.map((s) => renderSceneRpy(s, project)).join("\n");
  return [`# ${project.name}\n# ${project.description}\n`, begin, scenes].join("\n");
}

export function renderOptionsRpy(project: Project): string {
  return [
    `## ${project.name} - Options`,
    `define config.name = _("${safeText(project.name)}")`,
    `define gui.show_name = True`,
    `define config.version = "0.1.0"`,
    `define gui.about = _p("""`,
    `${project.description}`,
    `Created with VN Builder Studio.`,
    `""")`,
    `define build.name = "${slug(project.name)}"`,
    "",
  ].join("\n");
}

export function renderScreensRpy(): string {
  // Minimal: rely on Ren'Py's default screens.rpy from a fresh project.
  // We emit a small override file that doesn't conflict.
  return [
    "# screens.rpy overrides (intentionally minimal)",
    "# Create a new Ren'Py project, copy default screens.rpy from there,",
    "# then merge with these files.",
    "",
  ].join("\n");
}

export function buildRenpyProject(project: Project): Record<string, string> {
  return {
    "game/script.rpy": renderScriptRpy(project),
    "game/characters.rpy": renderCharactersRpy(project),
    "game/options.rpy": renderOptionsRpy(project),
    "game/screens_overrides.rpy": renderScreensRpy(),
    "README.txt": [
      `${project.name}`,
      ``,
      project.description,
      ``,
      `Exported from VN Builder Studio.`,
      ``,
      `Build steps:`,
      `1. Open Ren'Py SDK and click "+ Create New Project" once to generate the default game/ skeleton if you don't already have one.`,
      `2. Copy the files in this folder's game/ into your Ren'Py project's game/ folder.`,
      `3. Add character expression PNGs into game/images/<character>/<expression>.png`,
      `4. Run the project from the Ren'Py SDK to test, then "Build Distributions" for .exe.`,
    ].join("\n"),
  };
}
